function T = bad_nodes_table(report)
    mask = report.bad_mask | report.warning_mask;
    if ~any(mask)
        T = table();
        return
    end

    nodeIndex = find(mask);
    nrows = numel(nodeIndex);
    failureLabel = strings(nrows, 1);
    for i = 1:nrows
        failureLabel(i) = failure_code_label(report.failure_code(nodeIndex(i)));
    end

    T = table( ...
        repmat(string(report.label), nrows, 1), ...
        nodeIndex(:), ...
        report.patch_id(nodeIndex), ...
        report.r(1, nodeIndex).', ...
        report.r(2, nodeIndex).', ...
        report.r(3, nodeIndex).', ...
        report.normal_cross_dot(nodeIndex), ...
        report.jac(nodeIndex), ...
        report.jac_ratio_to_ref(nodeIndex), ...
        report.mean_curv(nodeIndex), ...
        report.displacement_to_ref(nodeIndex), ...
        failureLabel, ...
        'VariableNames', {'surface_label', 'node_index', ...
        'patch_index', 'x', 'y', 'z', 'normal_cross_dot', 'jac', ...
        'jac_ratio_to_ref', 'mean_curv', 'displacement_to_ref', ...
        'failure_label'});
end


function txt = failure_code_label(code)
    switch code
        case 5
            txt = "nonfinite";
        case 4
            txt = "normal_cross";
        case 3
            txt = "jac_ratio_fail";
        case 2
            txt = "curvature";
        case 1
            txt = "jac_ratio_warn";
        otherwise
            txt = "ok";
    end
end
