function settings = default_settings()
%DEFAULT_SETTINGS Fixed-source smoothing and edge-blend controls.
settings = struct('rlam',2,'adapt_sigma',1,'two_stage_smoother',true,'newton_recovery',true, ...
    'c_eps',0.5,'c_rad',2.7,'c_tau',1.05,'sigmaFloorRel',1e-12, ...
    'distanceFloor',1e-300,'selectedEdgeIds',[], ...
    'preview_order',6,'preview_level',0,'orders',[4 6 8],'levels',[1 2 3]);
end
