function h = plot_gidmsh(ax, scaffold, mode)
    hold(ax, 'on');
    faces = double(scaffold.tris.');
    nodes = double(scaffold.nodes);
    switch mode
        case 'solid'
            h = trisurf(faces, nodes(1, :), nodes(2, :), nodes(3, :), ...
                zeros(1, size(nodes, 2)), 'Parent', ax, ...
                'FaceColor', [0.72 0.76 0.80], ...
                'FaceAlpha', 0.78, ...
                'EdgeColor', [0.05 0.05 0.05], ...
                'EdgeAlpha', 0.45, ...
                'LineWidth', 0.6, ...
                'AmbientStrength', 0.55, ...
                'DiffuseStrength', 0.55, ...
                'SpecularStrength', 0.05);
        case 'wireframe'
            h = trisurf(faces, nodes(1, :), nodes(2, :), nodes(3, :), ...
                zeros(1, size(nodes, 2)), 'Parent', ax, ...
                'FaceColor', 'none', ...
                'EdgeColor', [0.02 0.02 0.02], ...
                'EdgeAlpha', 0.28, ...
                'LineWidth', 0.45, ...
                'HitTest', 'off');
        otherwise
            error('edgepreserve:badScaffoldMode', ...
                'Unknown scaffold plot mode "%s".', mode);
    end
end
