function print_validity_report(report)
    status = 'PASS';
    if ~report.is_valid
        status = 'FAIL';
    elseif report.has_warnings
        status = 'WARN';
    end

    fprintf('\nBIE surface validity report: %s [%s]\n', ...
        report.label, status);
    fprintf('  npts=%d, npatches=%d\n', ...
        report.stats.npts, report.stats.npatches);
    fprintf('  n dot normalize(du x dv) min/mean/max = %.6e %.6e %.6e\n', ...
        report.stats.normal_cross_dot_min, ...
        report.stats.normal_cross_dot_mean, ...
        report.stats.normal_cross_dot_max);
    fprintf('  |du x dv| min/mean/max = %.6e %.6e %.6e\n', ...
        report.stats.jac_min, report.stats.jac_mean, ...
        report.stats.jac_max);
    if report.has_reference
        fprintf('  jac/ref min/mean/max = %.6e %.6e %.6e\n', ...
            report.stats.jac_ratio_min, report.stats.jac_ratio_mean, ...
            report.stats.jac_ratio_max);
        fprintf('  displacement to ref min/mean/max/std = %.6e %.6e %.6e %.6e\n', ...
            report.stats.displacement_min, report.stats.displacement_mean, ...
            report.stats.displacement_max, report.stats.displacement_std);
    end
    fprintf('  weights min/mean/max = %.6e %.6e %.6e\n', ...
        report.stats.wts_min, report.stats.wts_mean, ...
        report.stats.wts_max);
    fprintf('  mean curvature min/mean/max/std = %.6e %.6e %.6e %.6e\n', ...
        report.stats.mean_curv_min, report.stats.mean_curv_mean, ...
        report.stats.mean_curv_max, report.stats.mean_curv_std);
    fprintf('  bad nodes/patches = %d/%d, warnings nodes/patches = %d/%d\n', ...
        report.stats.bad_node_count, report.stats.bad_patch_count, ...
        report.stats.warning_node_count, report.stats.warning_patch_count);
    if ~report.is_valid
        fprintf(['  failure counts: nonfinite=%d, normal=%d, ', ...
            'jac_ratio=%d, curvature=%d\n'], ...
            report.stats.bad_finite_count, report.stats.bad_normal_count, ...
            report.stats.bad_jac_ratio_count, ...
            report.stats.bad_curvature_count);
    end
end
